### ISSUE TITLE
[Request] Props for time already lapsed

### ISSUE THREAD

**Issue by yarnball** [react-z/react-timer#7]
Hi,

I'd like to be able to save how many seconds have passed. For example, I might send this value to my server. Then when the timer loads, it could put "Seconds Passed" into props.

Is this feature possible?

Thanks

**Comment by StevenIseki** [comment]
Probably having an `onTimeUpdate()` function passed as a prop to `react-timer` which fires in the update function. Not sure if that would fire too often though. It would be easy to implement.

**Comment by yarnball** [comment]
Ok great. I'm pretty new to react/coding- would you have any directions for me?

**Comment by StevenIseki** [comment]
Add the following, you can use this as an example https://github.com/StevenIseki/react-tab-view/blob/master/src/tabs.js

```js
static get propTypes () {
    return {
      onTimeUpdate: PropTypes.func
    }
  }
```

```js
if (this.props.onTimeUpdate !== undefined) {
  this.props.onTimeUpdate(time)
}
```

Init the component like this

`<Timer onTimeUpdate={myfunc} />`

If you want to make a pr, fork this, update and then submit the pr. I can look at it in a few days. Or you can use your forked version, just update in your package.json.
